### ISSUE TITLE
🤞Roadmap

### ISSUE THREAD

**Issue by drcmda** [react-spring/react-use-gesture#45]
## v7

Read #109 for more

## v6.0.x
- [x] Renaming gesture keys

[Breaking changes](https://github.com/react-spring/react-use-gesture/blob/master/CHANGELOG.md#breaking-1)

## v5.1.x and v5.2.x
- [x] support for zoom on trackpads
- [x] support for pinch on trackpads on Safari
- [x] Typescript rewrite
- [x] Commodity handlers `useDrag`, `usePinch`, etc.

## v5.0.x
- [x] rename repo to react-use-gesture (?)
- [x] support for scroll events
- [x] hover/mousemove events without click / dragging
- [x] support for wheel events
- [x] support for pinch (touch only)
- [x] enabling / disabling gestures dynamically
- [x] tests

**Comment by schabluk** [comment]
@drcmda hi, is there a plan to support other native DnD events? Like:

```
onDragEnter
onDragExit
onDragOver
onDrop
onDragStart
onDragEnd
```

Using them with together with useGesture breaks the effect.

**Comment by drcmda** [comment]
@dbismut do we cover those?

**Comment by dbismut** [comment]
@drcmda I'm not sure about the question: we're not covering dnd events, but the lib shouldn't break them though. But there's no plan in supporting dnd handlers as useGesture is generally used to simplify gesture-based interaction with out-of-the box detection for drag / pinch gestures but not as as dnd replacement library. Unless you think otherwise?

@schabluk do you mind opening an issue with a codesandbox showing the problem?

**Comment by schabluk** [comment]
@dbismut please, see this example: https://codesandbox.io/s/eloquent-yalow-0kv87

I am using `draggable`  attribute together with `onDragOver` to capture the index of the element over which I'm dragging. Than breaks the interaction. If you set `draggable={false}` the spring animation is working correctly.

**Comment by alihassan0** [comment]
Hello , Thanks for the libarary. 
I was wondering wether that means as of version v5.1.1 that typescript is supported. 
I just tried the libarary for the first time today in a new create react app typescript project and I got the following error 
```
Module '"../node_modules/react-use-gesture/web.cjs"' has no exported member 'useGesture'
```
so I am guessing typescript typing are unreliable right ?

**Comment by dbismut** [comment]
Damn I suck at TS. I’ll have a look later tonight. Really sorry about this.

**Comment by dbismut** [comment]
I’m OOH and left my charger. This will have to wait til Wednesday I’m afraid.

**Comment by alihassan0** [comment]
No problems .. thanks for taking the time. 
I excluded the library types in tsconfig which seems to solve the issue for now

**Comment by dbismut** [comment]
@tim-soft as a matter of fact, `onPinch` already exists and works for trackpads, check this example out: https://codesandbox.io/s/9o92o24wrr

It should zoom properly on Chrome and Firefox. If you have a Mac and using Safari, then you should also be able to scale _and_ rotate. This can only happen when you use the `domTarget` option, as `gesturechange` handlers are required to be added to the dom node directly (vs. passed as props when not using that option), and `gesturechange` or any Safari proprietary handlers are not supported in React (ie `onGestureChange` is not a valid prop).

**Comment by dbismut** [comment]
Ohhh ok sorry my bad. I guess that should be doable indeed. Note that in v6, `onWheel` would no longer be fired when `onPinch` is run (ie when `ctrlKey` flag is `true`), and I understand that might be an issue in your case. Let me think on this.

Very cool component by the way!

**Comment by dbismut** [comment]
Hey @tim-soft I just took some time to investigate your problem. As far as I understand, panning can only be achieved through `wheel` events, so there's no real way to distinguish wheel from two fingers moving on the trackpad. In this [example](https://stackblitz.com/edit/multi-touch-trackpad-gesture), panning only occurs through `wheel` events.

However, I think you can improve the swipe detection on a trackpad by reading this issue #85 and this sandbox: https://codesandbox.io/s/onwheel-fire-once-5urx7
